version: "2"
services:
    rasp-ubuntu-mdb:
      privileged: true
      image: yobasystems/alpine-mariadb:latest
      ports:
        - "33306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: go-perun-rest-api
        MYSQL_USER: rest-api
        MYSQL_PASSWORD: rest-api
      volumes:
        - "./data/mariadb:/var/lib/mysql"
        - "./init:/docker-entrypoint-initdb.d"
      restart: always
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci