/*
 * ODS
 *
 * This is a simple REST API to access Block Chain on Ethereum and handling Smart Contracts and Payment Channel as well.
 *
 * API version: 1.0.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

//User does
type User struct {
	ID string `json:"id,omitempty"`

	Alias string `json:"alias,omitempty"`

	Secret string `json:"secret,omitempty"`

	SecretKey string `json:"secret_key,omitempty"`

	PrivateKey string `json:"private_key,omitempty"`
}
