/*
 * ODS
 *
 * This is a simple REST API to access Block Chain on Ethereum and handling Smart Contracts and Payment Channel as well.
 *
 * API version: 1.0.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

//User does
type UserSession struct {
	Alias string `json:"alias,omitempty"`

	Ip_Addr string `json:"ip_addr,omitempty"`

	Port int16 `json:"port,omitempty"`
}
