/*
 * ODS
 *
 * This is a simple REST API to access Block Chain on Ethereum and handling Smart Contracts and Payment Channel as well.
 *
 * API version: 1.0.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

//ModelError hold information about any error
type ModelError struct {
	ShortMessage string `json:"shortMessage,omitempty"`

	LongMessage string `json:"longMessage,omitempty"`

	Error error `json:"error,omitempty"`
}
