/*
 * ODS
 *
 * This is a simple REST API to access Block Chain on Ethereum and handling Smart Contracts and Payment Channel as well.
 *
 * API version: 1.0.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

import "time"

//SimpleDataProtocol holds an entry for a specific part in the federator-client communication
type SimpleDataProtocol struct {
	ID int64 `json:"id,omitempty"`

	SenderAlias string `json:"sender_alias,omitempty"`

	ReceiverAlias string `json:"receiver_alias,omitempty"`
	// Id which refers to the message ID of a requested action in a specific payment channel
	MsgId uint32 `json:"msg_id,omitempty"`

	PaymentChannel uint64 `json:"payment_channel,omitempty"`
	// Id which refers to the message ID which is the response in a specific payment channel
	MsgIdRef uint32 `json:"msg_id_ref,omitempty"`

	Data string `json:"data,omitempty"`

	LastUpdated time.Time `json:"last_updated,omitempty"`
}
