# required for go server
go get github.com/gorilla/mux

# required for example script deploy contract
go get github.com/VictoriaMetrics/fastcache
go get github.com/aristanetworks/goarista/monotime
go get github.com/davecgh/go-spew/spew
go get github.com/deckarep/golang-set
go get github.com/edsrzf/mmap-go
go get github.com/gballet/go-libpcsclite
go get github.com/go-stack/stack
go get github.com/golang/protobuf/proto
go get github.com/golang/protobuf/protoc-gen-go/descriptor
go get github.com/gorilla/websocket
go get github.com/hashicorp/golang-lru
go get github.com/hashicorp/golang-lru/simplelru
go get github.com/holiman/uint256
go get github.com/huin/goupnp
go get github.com/huin/goupnp/dcps/internetgateway1
go get github.com/huin/goupnp/dcps/internetgateway2
go get github.com/jackpal/go-nat-pmp
go get github.com/karalabe/usb
go get github.com/olekukonko/tablewriter
go get github.com/pborman/uuid
go get github.com/peterh/liner
go get github.com/prometheus/tsdb/fileutil
go get github.com/rjeczalik/notify
go get github.com/shirou/gopsutil/cpu
go get github.com/status-im/keycard-go/derivationpath
go get github.com/steakknife/bloomfilter
go get github.com/syndtr/goleveldb/leveldb
go get github.com/syndtr/goleveldb/leveldb/errors
go get github.com/syndtr/goleveldb/leveldb/filter
go get github.com/syndtr/goleveldb/leveldb/iterator
go get github.com/syndtr/goleveldb/leveldb/opt
go get github.com/syndtr/goleveldb/leveldb/storage
go get github.com/syndtr/goleveldb/leveldb/util
go get github.com/tyler-smith/go-bip39
go get github.com/wsddn/go-ecdh
go get golang.org/x/crypto/hkdf
go get golang.org/x/crypto/pbkdf2
go get golang.org/x/crypto/ripemd160
go get golang.org/x/crypto/scrypt
go get golang.org/x/crypto/sha3
go get golang.org/x/sys/cpu
go get golang.org/x/text/unicode/norm
go get github.com/ethereum/go-ethereum/common
go get github.com/perun-network/go-perun/wallet
go get github.com/perun-network/go-perun/client
go get github.com/perun-network/go-perun/wire
go get github.com/perun-network/go-perun/channel
go get github.com/perun-network/perun-eth-demo/cmd
