version: "2"
services:
  ubuntu-arm64v8-api:
    privileged: true
    image: ubuntu-arm64v8-api:latest
    ports:
      - "8001:8080"
    mem_limit: 512M
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./log:/home/ubuntu/log"
    restart: always
    environment:
      BLOCKCHAIN: ws://192.168.2.136:8546
      DATABASE: 192.168.2.5
      EXTERNAL_IP: ${EXTERNAL_IP}
