version: "2"
services:
  ubuntu-arm-32-boot:
    privileged: true
    image: ubuntu-arm32v7-eth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "6060:6060"
      - "30303:30303"
    environment:
      TERM: xterm
      NODETYPE: bootnode
      EXTIP_BOOTNODE: 192.168.1.5
      INTIP_BOOTNODE: 192.168.1.5
      GASPRICE: 10
      NETWORKID: 2000420101
      ENODE: TODO_CHECKOUT_AFTER_START
      MINER_HASH: 1e66d21a5beadc6afeb9a74e9703eab207da27f2
    mem_limit: 2500M
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data-boot/:/home/ubuntu/data"
      - "./log-boot:/home/ubuntu/log"
  ubuntu-arm-32-miner:
    privileged: true
    image: ubuntu-arm32v7-eth:latest
    ports:
        - "30304:30304"
    environment:
      NODETYPE: miner
      EXTIP_BOOTNODE: 192.168.1.5
      INTIP_BOOTNODE: 192.168.1.5
      EXTIP_MINER: 192.168.1.4
      EXTPORT_MINER: 30304      
      GASPRICE: 10
      NETWORKID: 2000420101
      ENODE: 4cf4d494d5f80d5917511511ec9bcb106eff20f9d122ce0d1f8b2a8fd17a03a073797d90d3521a2982255b2c2fcaae15a867eb012729ed2dc7fb3380080554bf
      MINER_HASH: 1e66d21a5beadc6afeb9a74e9703eab207da27f2
    mem_limit: 2500M
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./log-miner:/home/ubuntu/log"
  ubuntu-arm-32-miner2:
    privileged: true
    image: ubuntu-arm32v7-eth:latest
    ports:
        - "30305:30305"
    environment:
      NODETYPE: miner2
      EXTIP_BOOTNODE: 192.168.1.5
      INTIP_BOOTNODE: 192.168.1.5
      EXTIP_MINER: 192.168.1.4
      EXTPORT_MINER: 30305
      GASPRICE: 10
      NETWORKID: 2000420101
      ENODE: 4cf4d494d5f80d5917511511ec9bcb106eff20f9d122ce0d1f8b2a8fd17a03a073797d90d3521a2982255b2c2fcaae15a867eb012729ed2dc7fb3380080554bf
      MINER_HASH: 1e66d21a5beadc6afeb9a74e9703eab207da27f2
    mem_limit: 2500M
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./log-miner2:/home/ubuntu/log"
