/*
 * ODS
 *
 * This is a simple REST API to access Block Chain on Ethereum and handling Smart Contracts and Payment Channel as well.
 *
 * API version: 1.0.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
	"time"

	"github.com/rs/zerolog/log"
)

//Logger is called after eachsucessful routed web request
func Logger(inner http.Handler, name string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		inner.ServeHTTP(w, r)
		duration := time.Since(start)

		log.Info().
			Str("method", r.Method).
			Str("requestUri", r.RequestURI).
			Str("name", name).
			Str("durationAsStr", duration.String()).
			Uint64("durationAsInt", uint64(duration)).
			Msg("request finished")

		log.Info().Msgf(
			"request finished: %s %s %s %s (%d)",
			r.Method,
			r.RequestURI,
			name,
			duration,
			duration,
		)
	})
}
