version: "2"
services:
  ubuntu-arm-64-boot:
    privileged: true
    image: ubuntu-arm64v8-eth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "6060:6060"
      - "30303:30303"
    environment:
      TERM: xterm
      NODETYPE: bootnode
      EXTIP_BOOTNODE: 192.168.2.136
      INTIP_BOOTNODE: 192.168.2.136
      GASPRICE: 10
      NETWORKID: 2000420101
      ENODE: TODO_CHECKOUT_AFTER_START
      MINER_HASH: 1e66d21a5beadc6afeb9a74e9703eab207da27f2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/home/ubuntu/data"
      - "./log:/home/ubuntu/log"
  ubuntu-arm-64-miner:
    privileged: true
    image: ubuntu-arm64v8-eth:latest
    ports:
        - "30304:30304"
    environment:
      NODETYPE: miner
      EXTIP_BOOTNODE: 192.168.2.136
      INTIP_BOOTNODE: 192.168.2.136
      EXTIP_MINER: 192.168.2.136
      EXTPORT_MINER: 30304
      GASPRICE: 10
      NETWORKID: 2000420101
      ENODE: 2ba0a02883a9a91e109cfa98eb8ce16fc4b10483d93b211db10594076896728d27eeabbc66b9ceb0831786d48e633cbf3801eaed90891ba8593cb673f14cda4f
      MINER_HASH: 1e66d21a5beadc6afeb9a74e9703eab207da27f2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/home/ubuntu/data"
      - "./log:/home/ubuntu/log"
  ubuntu-arm-64-miner2:
    privileged: true
    image: ubuntu-arm64v8-eth:latest
    ports:
        - "30305:30305"
    environment:
      NODETYPE: miner2
      EXTIP_BOOTNODE: 192.168.2.136
      INTIP_BOOTNODE: 192.168.2.136
      EXTIP_MINER: 192.168.2.136
      EXTPORT_MINER: 30305
      GASPRICE: 10
      NETWORKID: 2000420101
      ENODE: 2ba0a02883a9a91e109cfa98eb8ce16fc4b10483d93b211db10594076896728d27eeabbc66b9ceb0831786d48e633cbf3801eaed90891ba8593cb673f14cda4f
      MINER_HASH: 1e66d21a5beadc6afeb9a74e9703eab207da27f2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/home/ubuntu/data"
      - "./log:/home/ubuntu/log"
